name: Minimal Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Echo Test
        shell: bash
        run: |
          echo "Testing runner connection"
          echo "Current location:"
          pwd
