name: Simple Runner Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  simple-test:
    runs-on: self-hosted
    
    steps:
    - name: Basic Test
      run: |
        echo "Hello from runner"
        pwd
        dir
