name: Minimal Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Echo Test
        shell: pwsh
        run: |
          Write-Host "Testing runner connection"
          Write-Host "Current location:"
          Get-Location
